version: '3.7'

services:
  mysql:
    image: mysql:8.0
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: resourcedb
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    domainname: opensearch-node1.com
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net

  opensearch-node2:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    domainname: opensearch-node2.com
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    domainname: opensearch-dashboards.com
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net

  web:
    build: .
    command: ["python", "-O", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - mysql
      - opensearch-node1
      - opensearch-node2
      - opensearch-dashboards
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    volumes:
      # The order is important: UI_SOURCE must be before python source
      - type: bind
        source: .
        target: /app/resourcedb
      - type: bind
        source: /tmp
        target: /app/tmp
    env_file:
        - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - opensearch-net

volumes:
  mysqldata:
  resourcedb:
  opensearch-data1:
  opensearch-data2:

networks:
    opensearch-net:
